# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/diamant/Scrivania/Matrix_Multiplication_in_FPGA/Matrix_Multiplication_in_FPGA.srcs/sources_1/ip/c_mio_sommatore/c_mio_sommatore.xci
# IP: The module: 'c_mio_sommatore' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/diamant/Scrivania/Matrix_Multiplication_in_FPGA/Matrix_Multiplication_in_FPGA.gen/sources_1/ip/c_mio_sommatore/c_mio_sommatore_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_mio_sommatore'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/diamant/Scrivania/Matrix_Multiplication_in_FPGA/Matrix_Multiplication_in_FPGA.srcs/sources_1/ip/c_mio_sommatore/c_mio_sommatore.xci
# IP: The module: 'c_mio_sommatore' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/diamant/Scrivania/Matrix_Multiplication_in_FPGA/Matrix_Multiplication_in_FPGA.gen/sources_1/ip/c_mio_sommatore/c_mio_sommatore_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_mio_sommatore'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
